name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2  # Pulls the repository code

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username stored as a GitHub secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub password stored as a GitHub secret

    - name: Build the Docker Image
      run: |
        docker build -t <dockerhub-username>/main:latest .

    - name: Push the Docker Image
      run: |
        docker push <dockerhub-username>/main:latest
