name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 1. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g., us-east-1

      # 2. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      # 3. Set up QEMU (if you need multi-arch builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 4. Set up Docker Buildx (if you want advanced build features)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Build & push the image to ECR
      - name: Build and Push to ECR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/adir/docker:latest
          # If you also want to push a version tag like the Git commit SHA, you could add:
          # tags: |
          #   ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/<REPO_NAME>:latest
          #   ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/<REPO_NAME>:$GITHUB_SHA
